psexec \\10.128.226.220 -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\Cshare.bat -b
psexec \\BCA_DBN_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\BCA_JHB_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\BFSDBNUMHSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\BRAJHBISASS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\BRAJHBISAVS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\CJDMENLYN.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\EPC-CJDCENT.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\EPC-CJDWON.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\EPC-FOUNTS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\EPC-MBWDB.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\EPC-MCCENT.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\EPC-MENLSC.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\EPC-MITHAT.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\EPC-MITMID.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\EPC-PARTS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\EPCWITBANK.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\GMDTD035243.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\GMS_MENLYN_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\GMS_MONT_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\INYANGAFS1.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\INYANGAFS3.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\LEX_MID_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\LRV_CKLF_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\LRV_MID_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCCPTGOOLRSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCCPTN1CTOSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCCPTPARVCSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCCPTPARVCVS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCCPTPLUSUSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCDBNCENLRSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCDBNGRVTOSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCDBNGRVTOVS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCDBNMOBTOSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCEMPINYMESS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCEMPINYMEVS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCJHBALBCVSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCJHBBOKNSSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCJHBBOKNSVS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCJHBGERNSSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCJHBSBYHTSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCKIMCBDKISS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCKIMCBDKIVS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCKZNDBNTYSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCKZNPMBHTSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCKZNPMBTYSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCKZNPMBTYVS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCLIMPOLVCSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCOFSBLMSUSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCOFSBLMVCSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCOFSBLMVCVS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCPTAARCTOSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCPTACENVCSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCPTACENVCVS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCPTAGEZFISS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCPTAGEZVWSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCPTAGEZVWVS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCPTAMENSUSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCPTAMENSUVS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCPTAPRPTOSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCPTASILGMDT017.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCVRYINYMESS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MCVRYINYMEVS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MDCMMHDHO001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MFSICT01.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MGMHATSERVER1.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MMHJHBFORSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MMHJHBFORVS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MMHPTAFORSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MMHWITCJDSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MMHWITMBZSS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MMHWITMBZVS001.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MNSNFLTACT01.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MNSNIPG01.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\MTYMIDSERVER1.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\NSN_ENDS_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\NSN_WOOD_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\TOY_BALL_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\TOY_BRUMA_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\TOY_CENT_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\TOY_EDEN_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\TOY_EMP_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\toy_gez_ps.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\TOY_HAT_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\TOY_KING_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\TOY_LYNN_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\TOY_N1C_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\TOY_PAARL_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\TOY_PAR_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\TOY_PTN_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\TOY_SINO_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\TOY_TABLE_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\TOY_TRPTN_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\TOY_VERM_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\TOY_WOOD_PS.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\ZA016370S00011.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
psexec \\ZA016480S00010.mccarthyltd.local -c -d -n 20 -s    \\mmhjhbisoav001.mccarthyltd.local\distribution\createshare.bat -b
