@ECHO OFF
ECHO Setting Parameters...

REM Setting general files parameters
SET MSIROOTFOLDER=c:\software
SET MSILOCATION=%MSIROOTFOLDER%\Service and Portal
SET MSIFILENAME=Service and Portal.msi
SET LOGFILENAME=%MSIFILENAME%.%date:~10,4%%date:~4,2%%date:~7,2%-%time:~0,2%_%time:~3,2%_%time:~6,2%.log

REM Setting machine name and domain name (might not be relevant to an expanded farm)
SET MACHINENAME=%COMPUTERNAME%
SET DOMAINNAME=MCCARTHY

REM Setting Setup Parameters

REM Will install MIM without PAM
SET FEATURES_TO_INSTALL=ALL
SET FEATURES_TO_EXCLUDE=PAMServices
SET MAIL_SERVER=%MACHINENAME%
SET SQLSERVER_SERVER=%MACHINENAME%
SET SERVICE_ACCOUNT_NAME=MIMService
SET SERVICE_ACCOUNT_PASSWORD=M!Mservice1001
SET SERVICE_ACCOUNT_DOMAIN=%DOMAINNAME%
SET SERVICE_ACCOUNT_EMAIL=Administrator@%DOMAINNAME%.co.za
SET RUNNING_USER_EMAIL=Administrator@%DOMAINNAME%.co.za
SET SYNCHRONIZATION_SERVER_ACCOUNT=%DOMAINNAME%\MIMSync
SET SYNCHRONIZATION_SERVER=%MACHINENAME%
SET SERVICEADDRESS=%MACHINENAME%
SET SHAREPOINTUSERS_CONF=1
SET REGISTRATION_ACCOUNT=%DOMAINNAME%\MIMsspr
SET REGISTRATION_ACCOUNT_PASSWORD=M!Mservice1001
SET REGISTRATION_PORT=8080
SET REGISTRATION_SERVERNAME=%MACHINENAME%
SET REGISTRATION_PORTAL_URL=http://localhost:8080
SET RESET_ACCOUNT=%DOMAINNAME%\MIMsspr
SET RESET_ACCOUNT_PASSWORD=M!Mservice1001
SET RESET_PORT=8088
SET RESET_SERVERNAME=%MACHINENAME%
SET SHAREPOINT_URL=http://localhost
SET MIMPAM_ACCOUNT_DOMAIN=%DOMAINNAME%
SET IS_RESET_EXTRANET=Extranet
SET IS_REGISTRATION_EXTRANET=Extranet
SET ACCEPT_EULA=1
SET FIREWALL_CONF=1
SET SQMOPTINSETTING=1
SET REBOOT=ReallySuppress

ECHO Running Installation...

SET COMMAND=MSIEXEC /i "%MSILOCATION%\%MSIFILENAME%" MAIL_SERVER="%MAIL_SERVER%" SQLSERVER_SERVER="%SQLSERVER_SERVER%" SERVICE_ACCOUNT_NAME="%SERVICE_ACCOUNT_NAME%" ^
SERVICE_ACCOUNT_PASSWORD="%SERVICE_ACCOUNT_PASSWORD%" SERVICE_ACCOUNT_DOMAIN="%SERVICE_ACCOUNT_DOMAIN%" SERVICE_ACCOUNT_EMAIL="%SERVICE_ACCOUNT_EMAIL%" RUNNING_USER_EMAIL="%RUNNING_USER_EMAIL%" ^
SYNCHRONIZATION_SERVER_ACCOUNT="%SYNCHRONIZATION_SERVER_ACCOUNT%" SYNCHRONIZATION_SERVER="%SYNCHRONIZATION_SERVER%" SERVICEADDRESS="%SERVICEADDRESS%" SHAREPOINTUSERS_CONF=%SHAREPOINTUSERS_CONF% ^
REGISTRATION_ACCOUNT="%REGISTRATION_ACCOUNT%" REGISTRATION_ACCOUNT_PASSWORD="%REGISTRATION_ACCOUNT_PASSWORD%" REGISTRATION_PORT=%REGISTRATION_PORT% REGISTRATION_SERVERNAME="%REGISTRATION_SERVERNAME%" ^
IS_REGISTRATION_EXTRANET="%IS_REGISTRATION_EXTRANET%" REGISTRATION_PORTAL_URL="%REGISTRATION_PORTAL_URL%" RESET_ACCOUNT="%RESET_ACCOUNT%" RESET_ACCOUNT_PASSWORD="%RESET_ACCOUNT_PASSWORD%" RESET_PORT=%RESET_PORT% ^
RESET_SERVERNAME="%RESET_SERVERNAME%" IS_RESET_EXTRANET="%IS_RESET_EXTRANET%" SHAREPOINT_URL="%SHAREPOINT_URL%" ACCEPT_EULA=%ACCEPT_EULA% FIREWALL_CONF=%FIREWALL_CONF% SQMOPTINSETTING=%SQMOPTINSETTING% ^
ADDLOCAL=%FEATURES_TO_INSTALL% REMOVE=%FEATURES_TO_EXCLUDE% MIMPAM_ACCOUNT_DOMAIN="%MIMPAM_ACCOUNT_DOMAIN%" REBOOT="%REBOOT%" /l*v "%LOGFILENAME%"

REM Echoing and running the command
ECHO %COMMAND%
#%COMMAND%

REM Wait for a 10 seconds to enable to user to examine to msi install command
timeout 10
EXIT 0